### ISSUE TITLE
PSM

### ISSUE THREAD

**Issue by vanekroman** [vanekroman/MicroWeatherStation#1]
PSM jsme rozchodili, ale při od-komentování řádků níže (tedy zapnutí PSM) se data odešlou. Zařízení po sléze jde do "spánku" a poté se už neprobudí. Zařízení se dá probudit pouze pomocí WKUP.
[code for power saving mode setup](https://github.com/vanekroman/MicroWeatherStation/blob/029a1f7ffd1ae5419caf77dd076e1e6fd5e81b18/task1_AT_NB.py#L120C1-L126C51)

Dále jsem zkoušeli přepnou z CAT-M na NB-IoT viz odkaz na kód níže, ale tento příkaz nic nepřepne a technologie zůstane na CAT-M.
[code for switching LTE CAT-M to NB-IoT](https://github.com/vanekroman/MicroWeatherStation/blob/029a1f7ffd1ae5419caf77dd076e1e6fd5e81b18/task1_AT_NB.py#L100)

Síť typicky vrací:
  tau_time = 600 s
  active_time = 16 s

### vlastnosti připojení
```
Status: 5
RSRP: -117 dBm
RSSI: -102 dBm
SINR: 8.2 dB
RAT: LTE Cat.M
RSRQ: -7 dB
Operator: 23003
Band: LTE BAND 8
EARFCN: 3544
TAC: 9488
CellID: 41DCA
ECL: N/A
```

**Comment by Reecal** [comment]
Jak dlouho jste zkoušeli na zařízení čekat? Pokud vám síť vrací parametry tau_time=600s, tak by se mělo cca po 600 sekundách zařízení automaticky vzbudit. Dochází k tomuto nebo se zařízení nevzbudí vůbec?

**Comment by vanekroman** [comment]
Podařilo se mi to rozchodit do takové podoby, kdy zařízení
-> připojí -> pošle počáteční data -> čeká na "POWER DOWN" -> vzbudí se (zaznamená "APP RDY) -> poslání dat -> ...

Problém spočívat ve špatné interpretaci PSM technologie, myslel jsem, že chceme posílat hodnoty častěji, ale to podle všeho není pravda a ani není možné nýbrž nám síť poskytne vždy vysoká čísla času spánku.

### Opravdu nám to poskytne takto malé hodnoty času spánku:
```
1860133 -> AT+QPSMS?
1860152 <- +QPSMS: 1,,,"600","16"

OK
TAU TIME = 600

ACTIVE TIME= 16
```

Bylo také nutné inicializovat a poslat, při probuzení, všechny commandy, které posíláme před smyčkou. Z toho vyplívá, že se zařízení automaticky nepřipojí po probuzení.

**Comment by Reecal** [comment]
Super, že se vám to podařilo vyřešit. 
Možná bych jen zvážil, zda je toto vhodné řešení (PSM a TCP based MQTT) vzhledem k zadání projektu a ke zvolené technologii (LTE Cat-M - licenční technologie s paywallem). Tím nechci naznačit, že byste to měli nějak předělávat, jen se nad tím zamyslet a minimálně do toho dokumentu uvést proč jste volili takto a jaké to bude mít dopady ať už na cenu a na datové objemy.
